//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 05:58:39 PM EST 
//


package com.extemp.cem.profiles;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}mobile_activity" minOccurs="0"/&gt;
 *         &lt;element ref="{}activity_object" minOccurs="0"/&gt;
 *         &lt;element ref="{}value" minOccurs="0"/&gt;
 *         &lt;element ref="{}category" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mobileActivity",
    "activityObject",
    "value",
    "category"
})
@XmlRootElement(name = "Actiity")
public class Actiity {

    @XmlElement(name = "mobile_activity")
    protected String mobileActivity;
    @XmlElement(name = "activity_object")
    protected String activityObject;
    protected String value;
    protected String category;

    /**
     * Gets the value of the mobileActivity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobileActivity() {
        return mobileActivity;
    }

    /**
     * Sets the value of the mobileActivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobileActivity(String value) {
        this.mobileActivity = value;
    }

    /**
     * Gets the value of the activityObject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivityObject() {
        return activityObject;
    }

    /**
     * Sets the value of the activityObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivityObject(String value) {
        this.activityObject = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

}
