//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 05:58:39 PM EST 
//


package com.extemp.cem.profiles;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/MusicSchema.xsd}bandName" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/MusicSchema.xsd}musicType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bandName",
    "musicType"
})
@XmlRootElement(name = "Band", namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/MusicSchema.xsd")
public class Band {

    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/MusicSchema.xsd")
    protected String bandName;
    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/MusicSchema.xsd")
    protected String musicType;

    /**
     * Gets the value of the bandName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBandName() {
        return bandName;
    }

    /**
     * Sets the value of the bandName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBandName(String value) {
        this.bandName = value;
    }

    /**
     * Gets the value of the musicType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMusicType() {
        return musicType;
    }

    /**
     * Sets the value of the musicType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMusicType(String value) {
        this.musicType = value;
    }

}
