//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 05:58:39 PM EST 
//


package com.extemp.cem.profiles;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd}barName" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd}barAddress" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd}serverDrinksList" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "barName",
    "barAddress",
    "serverDrinksList"
})
@XmlRootElement(name = "Bar", namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd")
public class Bar {

    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd")
    protected String barName;
    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd")
    protected String barAddress;
    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd")
    protected ServerDrinksList serverDrinksList;

    /**
     * Gets the value of the barName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarName() {
        return barName;
    }

    /**
     * Sets the value of the barName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarName(String value) {
        this.barName = value;
    }

    /**
     * Gets the value of the barAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarAddress() {
        return barAddress;
    }

    /**
     * Sets the value of the barAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarAddress(String value) {
        this.barAddress = value;
    }

    /**
     * Gets the value of the serverDrinksList property.
     * 
     * @return
     *     possible object is
     *     {@link ServerDrinksList }
     *     
     */
    public ServerDrinksList getServerDrinksList() {
        return serverDrinksList;
    }

    /**
     * Sets the value of the serverDrinksList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerDrinksList }
     *     
     */
    public void setServerDrinksList(ServerDrinksList value) {
        this.serverDrinksList = value;
    }

}
