//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 05:58:39 PM EST 
//


package com.extemp.cem.profiles;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/FoodSchema.xsd}chefName" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/FoodSchema.xsd}chefCountryOfOrigin" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/FoodSchema.xsd}chefCookingStyle" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "chefName",
    "chefCountryOfOrigin",
    "chefCookingStyle"
})
@XmlRootElement(name = "Chef", namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/FoodSchema.xsd")
public class Chef {

    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/FoodSchema.xsd")
    protected String chefName;
    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/FoodSchema.xsd")
    protected String chefCountryOfOrigin;
    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/FoodSchema.xsd")
    protected String chefCookingStyle;

    /**
     * Gets the value of the chefName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChefName() {
        return chefName;
    }

    /**
     * Sets the value of the chefName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChefName(String value) {
        this.chefName = value;
    }

    /**
     * Gets the value of the chefCountryOfOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChefCountryOfOrigin() {
        return chefCountryOfOrigin;
    }

    /**
     * Sets the value of the chefCountryOfOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChefCountryOfOrigin(String value) {
        this.chefCountryOfOrigin = value;
    }

    /**
     * Gets the value of the chefCookingStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChefCookingStyle() {
        return chefCookingStyle;
    }

    /**
     * Sets the value of the chefCookingStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChefCookingStyle(String value) {
        this.chefCookingStyle = value;
    }

}
