//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 05:58:39 PM EST 
//


package com.extemp.cem.profiles;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/EntSchema.xsd}cinemaName" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/EntSchema.xsd}cinemaLocation" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/EntSchema.xsd}cinemaBrand" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cinemaName",
    "cinemaLocation",
    "cinemaBrand"
})
@XmlRootElement(name = "Cinema", namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/EntSchema.xsd")
public class Cinema {

    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/EntSchema.xsd")
    protected String cinemaName;
    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/EntSchema.xsd")
    protected String cinemaLocation;
    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/EntSchema.xsd")
    protected CinemaBrand cinemaBrand;

    /**
     * Gets the value of the cinemaName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCinemaName() {
        return cinemaName;
    }

    /**
     * Sets the value of the cinemaName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCinemaName(String value) {
        this.cinemaName = value;
    }

    /**
     * Gets the value of the cinemaLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCinemaLocation() {
        return cinemaLocation;
    }

    /**
     * Sets the value of the cinemaLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCinemaLocation(String value) {
        this.cinemaLocation = value;
    }

    /**
     * Gets the value of the cinemaBrand property.
     * 
     * @return
     *     possible object is
     *     {@link CinemaBrand }
     *     
     */
    public CinemaBrand getCinemaBrand() {
        return cinemaBrand;
    }

    /**
     * Sets the value of the cinemaBrand property.
     * 
     * @param value
     *     allowed object is
     *     {@link CinemaBrand }
     *     
     */
    public void setCinemaBrand(CinemaBrand value) {
        this.cinemaBrand = value;
    }

}
