//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 05:58:39 PM EST 
//


package com.extemp.cem.profiles;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd}drinkName" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd}drinkType" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd}drinkCategory" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd}drinkCountryofProvenance" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "drinkName",
    "drinkType",
    "drinkCategory",
    "drinkCountryofProvenance"
})
@XmlRootElement(name = "Drink", namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd")
public class Drink {

    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd")
    protected String drinkName;
    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd")
    protected String drinkType;
    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd")
    protected String drinkCategory;
    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd")
    protected String drinkCountryofProvenance;

    /**
     * Gets the value of the drinkName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrinkName() {
        return drinkName;
    }

    /**
     * Sets the value of the drinkName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrinkName(String value) {
        this.drinkName = value;
    }

    /**
     * Gets the value of the drinkType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrinkType() {
        return drinkType;
    }

    /**
     * Sets the value of the drinkType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrinkType(String value) {
        this.drinkType = value;
    }

    /**
     * Gets the value of the drinkCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrinkCategory() {
        return drinkCategory;
    }

    /**
     * Sets the value of the drinkCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrinkCategory(String value) {
        this.drinkCategory = value;
    }

    /**
     * Gets the value of the drinkCountryofProvenance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrinkCountryofProvenance() {
        return drinkCountryofProvenance;
    }

    /**
     * Sets the value of the drinkCountryofProvenance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrinkCountryofProvenance(String value) {
        this.drinkCountryofProvenance = value;
    }

}
