//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 05:58:39 PM EST 
//


package com.extemp.cem.profiles;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd}favouriteDrinkList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd}favouriteBarList"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "favouriteDrinkList",
    "favouriteBarList"
})
@XmlRootElement(name = "DrinkProfile", namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd")
public class DrinkProfile {

    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd")
    protected FavouriteDrinkList favouriteDrinkList;
    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd", required = true)
    protected FavouriteBarList favouriteBarList;

    /**
     * Gets the value of the favouriteDrinkList property.
     * 
     * @return
     *     possible object is
     *     {@link FavouriteDrinkList }
     *     
     */
    public FavouriteDrinkList getFavouriteDrinkList() {
        return favouriteDrinkList;
    }

    /**
     * Sets the value of the favouriteDrinkList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FavouriteDrinkList }
     *     
     */
    public void setFavouriteDrinkList(FavouriteDrinkList value) {
        this.favouriteDrinkList = value;
    }

    /**
     * Gets the value of the favouriteBarList property.
     * 
     * @return
     *     possible object is
     *     {@link FavouriteBarList }
     *     
     */
    public FavouriteBarList getFavouriteBarList() {
        return favouriteBarList;
    }

    /**
     * Sets the value of the favouriteBarList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FavouriteBarList }
     *     
     */
    public void setFavouriteBarList(FavouriteBarList value) {
        this.favouriteBarList = value;
    }

}
