//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 05:58:39 PM EST 
//


package com.extemp.cem.profiles;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/EntSchema.xsd}favouriteCinemaList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/EntSchema.xsd}favouriteFilmList"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "favouriteCinemaList",
    "favouriteFilmList"
})
@XmlRootElement(name = "EntertainmentProfile", namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/EntSchema.xsd")
public class EntertainmentProfile {

    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/EntSchema.xsd")
    protected FavouriteCinemaList favouriteCinemaList;
    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/EntSchema.xsd", required = true)
    protected FavouriteFilmList favouriteFilmList;

    /**
     * Gets the value of the favouriteCinemaList property.
     * 
     * @return
     *     possible object is
     *     {@link FavouriteCinemaList }
     *     
     */
    public FavouriteCinemaList getFavouriteCinemaList() {
        return favouriteCinemaList;
    }

    /**
     * Sets the value of the favouriteCinemaList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FavouriteCinemaList }
     *     
     */
    public void setFavouriteCinemaList(FavouriteCinemaList value) {
        this.favouriteCinemaList = value;
    }

    /**
     * Gets the value of the favouriteFilmList property.
     * 
     * @return
     *     possible object is
     *     {@link FavouriteFilmList }
     *     
     */
    public FavouriteFilmList getFavouriteFilmList() {
        return favouriteFilmList;
    }

    /**
     * Sets the value of the favouriteFilmList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FavouriteFilmList }
     *     
     */
    public void setFavouriteFilmList(FavouriteFilmList value) {
        this.favouriteFilmList = value;
    }

}
