//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 05:58:39 PM EST 
//


package com.extemp.cem.profiles;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/MLSE_BW_Engage_Infrastructure/ShareResources/XSD/Schema.xsd}game_name" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/MLSE_BW_Engage_Infrastructure/ShareResources/XSD/Schema.xsd}play" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gameName",
    "play"
})
@XmlRootElement(name = "GameFeed", namespace = "http://www.tibco.com/schemas/MLSE_BW_Engage_Infrastructure/ShareResources/XSD/Schema.xsd")
public class GameFeed {

    @XmlElement(name = "game_name", namespace = "http://www.tibco.com/schemas/MLSE_BW_Engage_Infrastructure/ShareResources/XSD/Schema.xsd")
    protected String gameName;
    @XmlElement(namespace = "http://www.tibco.com/schemas/MLSE_BW_Engage_Infrastructure/ShareResources/XSD/Schema.xsd")
    protected List<Play> play;

    /**
     * Gets the value of the gameName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGameName() {
        return gameName;
    }

    /**
     * Sets the value of the gameName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGameName(String value) {
        this.gameName = value;
    }

    /**
     * Gets the value of the play property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the play property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlay().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Play }
     * 
     * 
     */
    public List<Play> getPlay() {
        if (play == null) {
            play = new ArrayList<Play>();
        }
        return this.play;
    }

}
