//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 05:58:39 PM EST 
//


package com.extemp.cem.profiles;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/HealthSchema.xsd}allerygyList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/HealthSchema.xsd}illnessList" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "allerygyList",
    "illnessList"
})
@XmlRootElement(name = "HealthProfile", namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/HealthSchema.xsd")
public class HealthProfile {

    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/HealthSchema.xsd")
    protected AllerygyList allerygyList;
    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/HealthSchema.xsd")
    protected IllnessList illnessList;

    /**
     * Gets the value of the allerygyList property.
     * 
     * @return
     *     possible object is
     *     {@link AllerygyList }
     *     
     */
    public AllerygyList getAllerygyList() {
        return allerygyList;
    }

    /**
     * Sets the value of the allerygyList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllerygyList }
     *     
     */
    public void setAllerygyList(AllerygyList value) {
        this.allerygyList = value;
    }

    /**
     * Gets the value of the illnessList property.
     * 
     * @return
     *     possible object is
     *     {@link IllnessList }
     *     
     */
    public IllnessList getIllnessList() {
        return illnessList;
    }

    /**
     * Sets the value of the illnessList property.
     * 
     * @param value
     *     allowed object is
     *     {@link IllnessList }
     *     
     */
    public void setIllnessList(IllnessList value) {
        this.illnessList = value;
    }

}
