//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 05:58:39 PM EST 
//


package com.extemp.cem.profiles;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd}loyaltyUserId" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd}loyaltyProramName" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd}loyaltyTier" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd}totalAcumulatedPoints" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "loyaltyUserId",
    "loyaltyProramName",
    "loyaltyTier",
    "totalAcumulatedPoints"
})
@XmlRootElement(name = "loyaltyProgram", namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd")
public class LoyaltyProgram {

    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd")
    protected String loyaltyUserId;
    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd")
    protected String loyaltyProramName;
    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd")
    protected String loyaltyTier;
    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd")
    protected Long totalAcumulatedPoints;

    /**
     * Gets the value of the loyaltyUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoyaltyUserId() {
        return loyaltyUserId;
    }

    /**
     * Sets the value of the loyaltyUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoyaltyUserId(String value) {
        this.loyaltyUserId = value;
    }

    /**
     * Gets the value of the loyaltyProramName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoyaltyProramName() {
        return loyaltyProramName;
    }

    /**
     * Sets the value of the loyaltyProramName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoyaltyProramName(String value) {
        this.loyaltyProramName = value;
    }

    /**
     * Gets the value of the loyaltyTier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoyaltyTier() {
        return loyaltyTier;
    }

    /**
     * Sets the value of the loyaltyTier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoyaltyTier(String value) {
        this.loyaltyTier = value;
    }

    /**
     * Gets the value of the totalAcumulatedPoints property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTotalAcumulatedPoints() {
        return totalAcumulatedPoints;
    }

    /**
     * Sets the value of the totalAcumulatedPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTotalAcumulatedPoints(Long value) {
        this.totalAcumulatedPoints = value;
    }

}
