//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 05:58:39 PM EST 
//


package com.extemp.cem.profiles;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/MusicSchema.xsd}favouriteMusicTypeList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/MusicSchema.xsd}favouriteMusiciantList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/MusicSchema.xsd}favouriteBandList" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "favouriteMusicTypeList",
    "favouriteMusiciantList",
    "favouriteBandList"
})
@XmlRootElement(name = "MusicProfile", namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/MusicSchema.xsd")
public class MusicProfile {

    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/MusicSchema.xsd")
    protected FavouriteMusicTypeList favouriteMusicTypeList;
    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/MusicSchema.xsd")
    protected FavouriteMusiciantList favouriteMusiciantList;
    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/MusicSchema.xsd")
    protected FavouriteBandList favouriteBandList;

    /**
     * Gets the value of the favouriteMusicTypeList property.
     * 
     * @return
     *     possible object is
     *     {@link FavouriteMusicTypeList }
     *     
     */
    public FavouriteMusicTypeList getFavouriteMusicTypeList() {
        return favouriteMusicTypeList;
    }

    /**
     * Sets the value of the favouriteMusicTypeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FavouriteMusicTypeList }
     *     
     */
    public void setFavouriteMusicTypeList(FavouriteMusicTypeList value) {
        this.favouriteMusicTypeList = value;
    }

    /**
     * Gets the value of the favouriteMusiciantList property.
     * 
     * @return
     *     possible object is
     *     {@link FavouriteMusiciantList }
     *     
     */
    public FavouriteMusiciantList getFavouriteMusiciantList() {
        return favouriteMusiciantList;
    }

    /**
     * Sets the value of the favouriteMusiciantList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FavouriteMusiciantList }
     *     
     */
    public void setFavouriteMusiciantList(FavouriteMusiciantList value) {
        this.favouriteMusiciantList = value;
    }

    /**
     * Gets the value of the favouriteBandList property.
     * 
     * @return
     *     possible object is
     *     {@link FavouriteBandList }
     *     
     */
    public FavouriteBandList getFavouriteBandList() {
        return favouriteBandList;
    }

    /**
     * Sets the value of the favouriteBandList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FavouriteBandList }
     *     
     */
    public void setFavouriteBandList(FavouriteBandList value) {
        this.favouriteBandList = value;
    }

}
