//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 05:58:39 PM EST 
//


package com.extemp.cem.profiles;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.extemp.cem.profiles package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EventID_QNAME = new QName("", "EventID");
    private final static QName _UserID_QNAME = new QName("", "UserID");
    private final static QName _ActivityType_QNAME = new QName("", "ActivityType");
    private final static QName _Tstamp_QNAME = new QName("", "tstamp");
    private final static QName _BrowsedURL_QNAME = new QName("", "BrowsedURL");
    private final static QName _BrowsedItemName_QNAME = new QName("", "BrowsedItemName");
    private final static QName _BrowsedItemCategory_QNAME = new QName("", "BrowsedItemCategory");
    private final static QName _BrowsedItemID_QNAME = new QName("", "BrowsedItemID");
    private final static QName _BrowsedItemBrand_QNAME = new QName("", "BrowsedItemBrand");
    private final static QName _BrowsedItemPrice_QNAME = new QName("", "BrowsedItemPrice");
    private final static QName _BrowsedItemSize_QNAME = new QName("", "BrowsedItemSize");
    private final static QName _BrowsedItemGender_QNAME = new QName("", "BrowsedItemGender");
    private final static QName _PublishedContentCategory_QNAME = new QName("", "PublishedContentCategory");
    private final static QName _PublishedContentTopic_QNAME = new QName("", "PublishedContentTopic");
    private final static QName _PublishedContentURL_QNAME = new QName("", "PublishedContentURL");
    private final static QName _PublishedContentID_QNAME = new QName("", "PublishedContentID");
    private final static QName _PublishedContentData_QNAME = new QName("", "PublishedContentData");
    private final static QName _ExpiryDate_QNAME = new QName("", "ExpiryDate");
    private final static QName _IntentName_QNAME = new QName("", "IntentName");
    private final static QName _IntentId_QNAME = new QName("", "IntentId");
    private final static QName _EventId_QNAME = new QName("", "eventId");
    private final static QName _UserIdEvent_QNAME = new QName("", "userId_event");
    private final static QName _EventName_QNAME = new QName("", "eventName");
    private final static QName _EventType_QNAME = new QName("", "eventType");
    private final static QName _DeviceId_QNAME = new QName("", "deviceId");
    private final static QName _DevicePhoneNumber_QNAME = new QName("", "devicePhoneNumber");
    private final static QName _GeoLocationCoords_QNAME = new QName("", "geoLocationCoords");
    private final static QName _LocationName_QNAME = new QName("", "locationName");
    private final static QName _SeatNumber_QNAME = new QName("", "seatNumber");
    private final static QName _ItemName_QNAME = new QName("", "itemName");
    private final static QName _GameWin_QNAME = new QName("", "gameWin");
    private final static QName _EventScorePlayer_QNAME = new QName("", "eventScorePlayer");
    private final static QName _EventMessage_QNAME = new QName("", "eventMessage");
    private final static QName _ReqIdEvent_QNAME = new QName("", "reqId_event");
    private final static QName _ApplicationSrc_QNAME = new QName("", "applicationSrc");
    private final static QName _MobileActivity_QNAME = new QName("", "mobile_activity");
    private final static QName _ActivityObject_QNAME = new QName("", "activity_object");
    private final static QName _Value_QNAME = new QName("", "value");
    private final static QName _Category_QNAME = new QName("", "category");
    private final static QName _EntEventId_QNAME = new QName("", "ent_event_id");
    private final static QName _EntEventName_QNAME = new QName("", "ent_event_name");
    private final static QName _EntEventType_QNAME = new QName("", "ent_event_type");
    private final static QName _EntId_QNAME = new QName("", "ent_id");
    private final static QName _EntAppSource_QNAME = new QName("", "ent_app_source");
    private final static QName _EntUserId_QNAME = new QName("", "ent_user_id");
    private final static QName _EntActivity_QNAME = new QName("", "ent_activity");
    private final static QName _EntActivityObject_QNAME = new QName("", "ent_activity_object");
    private final static QName _EntActivityObjectUri_QNAME = new QName("", "ent_activity_object_uri");
    private final static QName _EntActivityCategory_QNAME = new QName("", "ent_activity_category");
    private final static QName _EntActivityContextCategory_QNAME = new QName("", "ent_activity_context_category");
    private final static QName _EntActivityContextContent_QNAME = new QName("", "ent_activity_context_content");
    private final static QName _Id_QNAME = new QName("", "id");
    private final static QName _UserIdNotification_QNAME = new QName("", "userId_notification");
    private final static QName _Type_QNAME = new QName("", "type");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _NotificationMessage_QNAME = new QName("", "notificationMessage");
    private final static QName _Source_QNAME = new QName("", "source");
    private final static QName _ReqIdNotification_QNAME = new QName("", "reqId_notification");
    private final static QName _ApplicationSrcNotification_QNAME = new QName("", "applicationSrc_notification");
    private final static QName _Payload_QNAME = new QName("", "payload");
    private final static QName _UserIdOfferReq_QNAME = new QName("", "userId_OfferReq");
    private final static QName _ReqIdOffer_QNAME = new QName("", "reqId_offer");
    private final static QName _UserName_QNAME = new QName("", "userName");
    private final static QName _Offer_QNAME = new QName("", "offer");
    private final static QName _OfferType_QNAME = new QName("", "offerType");
    private final static QName _ApplicationSrcOffer_QNAME = new QName("", "applicationSrc_offer");
    private final static QName _Approve_QNAME = new QName("", "approve");
    private final static QName _ProcessName_QNAME = new QName("", "process_name");
    private final static QName _ProcessExecutable_QNAME = new QName("", "process_executable");
    private final static QName _Pid_QNAME = new QName("", "pid");
    private final static QName _Status_QNAME = new QName("", "status");
    private final static QName _StartPhrase_QNAME = new QName("", "start_phrase");
    private final static QName _EndPhrase_QNAME = new QName("", "end_phrase");
    private final static QName _AttributeName_QNAME = new QName("", "attribute_name");
    private final static QName _AttributeValue_QNAME = new QName("", "attribute_value");
    private final static QName _ConnectUrl_QNAME = new QName("", "connect_url");
    private final static QName _JmsUser_QNAME = new QName("", "jms_user");
    private final static QName _JmsPass_QNAME = new QName("", "jms_pass");
    private final static QName _InDestName_QNAME = new QName("", "in_dest_name");
    private final static QName _InDestType_QNAME = new QName("", "in_dest_type");
    private final static QName _OutDestName_QNAME = new QName("", "out_dest_name");
    private final static QName _OutDestType_QNAME = new QName("", "out_dest_type");
    private final static QName _LogToConsole_QNAME = new QName("", "log_to_console");
    private final static QName _WaitForProcessEndMilis_QNAME = new QName("", "wait_for_process_end_milis");
    private final static QName _UserId_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", "userId");
    private final static QName _FirstName_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", "firstName");
    private final static QName _LastName_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", "lastName");
    private final static QName _Age_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", "age");
    private final static QName _CardNumber_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", "cardNumber");
    private final static QName _CardType_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", "cardType");
    private final static QName _IssuingBank_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", "issuingBank");
    private final static QName _Gender_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", "gender");
    private final static QName _MiddleName_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", "middleName");
    private final static QName _DateOfBirth_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", "dateOfBirth");
    private final static QName _Profession_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", "profession");
    private final static QName _FaceBookId_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", "faceBookId");
    private final static QName _LinkedInId_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", "linkedInId");
    private final static QName _TwitterId_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", "twitterId");
    private final static QName _StreetNum_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", "streetNum");
    private final static QName _City_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", "city");
    private final static QName _State_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", "state");
    private final static QName _Country_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", "country");
    private final static QName _LoyaltyUserId_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", "loyaltyUserId");
    private final static QName _LoyaltyProramName_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", "loyaltyProramName");
    private final static QName _LoyaltyTier_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", "loyaltyTier");
    private final static QName _TotalAcumulatedPoints_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", "totalAcumulatedPoints");
    private final static QName _LanguageSpoken_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", "languageSpoken");
    private final static QName _SportType_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/SportsSchema.xsd", "sportType");
    private final static QName _GeneralGameSentiment_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/SportsSchema.xsd", "generalGameSentiment");
    private final static QName _NumGamesAttendedSeason_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/SportsSchema.xsd", "numGamesAttendedSeason");
    private final static QName _NumGamesAttendedTotal_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/SportsSchema.xsd", "numGamesAttendedTotal");
    private final static QName _PlayerName_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/SportsSchema.xsd", "playerName");
    private final static QName _TeamName_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/SportsSchema.xsd", "teamName");
    private final static QName _FoodType_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/FoodSchema.xsd", "foodType");
    private final static QName _DishName_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/FoodSchema.xsd", "dishName");
    private final static QName _RestaurantName_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/FoodSchema.xsd", "restaurantName");
    private final static QName _RestaurantType_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/FoodSchema.xsd", "restaurantType");
    private final static QName _RestaurantAddress_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/FoodSchema.xsd", "restaurantAddress");
    private final static QName _ChefName_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/FoodSchema.xsd", "chefName");
    private final static QName _ChefCountryOfOrigin_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/FoodSchema.xsd", "chefCountryOfOrigin");
    private final static QName _ChefCookingStyle_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/FoodSchema.xsd", "chefCookingStyle");
    private final static QName _DrinkName_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd", "drinkName");
    private final static QName _DrinkType_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd", "drinkType");
    private final static QName _DrinkCategory_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd", "drinkCategory");
    private final static QName _DrinkCountryofProvenance_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd", "drinkCountryofProvenance");
    private final static QName _BarName_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd", "barName");
    private final static QName _BarAddress_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd", "barAddress");
    private final static QName _MusicType_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/MusicSchema.xsd", "musicType");
    private final static QName _MusicianName_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/MusicSchema.xsd", "musicianName");
    private final static QName _MusicianCountryOfOrigin_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/MusicSchema.xsd", "musicianCountryOfOrigin");
    private final static QName _MusicianStyle_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/MusicSchema.xsd", "musicianStyle");
    private final static QName _BandName_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/MusicSchema.xsd", "bandName");
    private final static QName _MerchandiseName_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/ShoppingSchema.xsd", "merchandiseName");
    private final static QName _MerchandiseType_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/ShoppingSchema.xsd", "merchandiseType");
    private final static QName _MerchandiseMaxPrice_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/ShoppingSchema.xsd", "merchandiseMaxPrice");
    private final static QName _MerchandiseSize_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/ShoppingSchema.xsd", "merchandiseSize");
    private final static QName _MerchandiseCategory_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/ShoppingSchema.xsd", "merchandiseCategory");
    private final static QName _StoreName_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/ShoppingSchema.xsd", "storeName");
    private final static QName _StoreLocation_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/ShoppingSchema.xsd", "storeLocation");
    private final static QName _Allergy_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/HealthSchema.xsd", "allergy");
    private final static QName _IllnessName_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/HealthSchema.xsd", "illnessName");
    private final static QName _UserIdSocial_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/SocialSchema.xsd", "userId_social");
    private final static QName _UserPassword_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/SocialSchema.xsd", "userPassword");
    private final static QName _UserRole_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/SocialSchema.xsd", "userRole");
    private final static QName _SocialAppName_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/SocialSchema.xsd", "socialAppName");
    private final static QName _SocialAppType_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/SocialSchema.xsd", "socialAppType");
    private final static QName _FriendName_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/SocialSchema.xsd", "friendName");
    private final static QName _FriendSocialGroup_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/SocialSchema.xsd", "friendSocialGroup");
    private final static QName _CinemaName_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/EntSchema.xsd", "cinemaName");
    private final static QName _CinemaLocation_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/EntSchema.xsd", "cinemaLocation");
    private final static QName _FilmName_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/EntSchema.xsd", "filmName");
    private final static QName _FilmCategory_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/EntSchema.xsd", "filmCategory");
    private final static QName _FilmDate_QNAME = new QName("http://www.tibco.com/schemas/CEM/SharedResources/XSD/EntSchema.xsd", "filmDate");
    private final static QName _GameName_QNAME = new QName("http://www.tibco.com/schemas/MLSE_BW_Engage_Infrastructure/ShareResources/XSD/Schema.xsd", "game_name");
    private final static QName _Time_QNAME = new QName("http://www.tibco.com/schemas/MLSE_BW_Engage_Infrastructure/ShareResources/XSD/Schema.xsd", "time");
    private final static QName _Period_QNAME = new QName("http://www.tibco.com/schemas/MLSE_BW_Engage_Infrastructure/ShareResources/XSD/Schema.xsd", "period");
    private final static QName _Team_QNAME = new QName("http://www.tibco.com/schemas/MLSE_BW_Engage_Infrastructure/ShareResources/XSD/Schema.xsd", "team");
    private final static QName _Detail_QNAME = new QName("http://www.tibco.com/schemas/MLSE_BW_Engage_Infrastructure/ShareResources/XSD/Schema.xsd", "detail");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.extemp.cem.profiles
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ActivityEvent }
     * 
     */
    public ActivityEvent createActivityEvent() {
        return new ActivityEvent();
    }

    /**
     * Create an instance of {@link ActivityEventList }
     * 
     */
    public ActivityEventList createActivityEventList() {
        return new ActivityEventList();
    }

    /**
     * Create an instance of {@link Intent }
     * 
     */
    public Intent createIntent() {
        return new Intent();
    }

    /**
     * Create an instance of {@link IntentList }
     * 
     */
    public IntentList createIntentList() {
        return new IntentList();
    }

    /**
     * Create an instance of {@link IntentList2 }
     * 
     */
    public IntentList2 createIntentList2() {
        return new IntentList2();
    }

    /**
     * Create an instance of {@link ActivityUser }
     * 
     */
    public ActivityUser createActivityUser() {
        return new ActivityUser();
    }

    /**
     * Create an instance of {@link ActivityEventListFull }
     * 
     */
    public ActivityEventListFull createActivityEventListFull() {
        return new ActivityEventListFull();
    }

    /**
     * Create an instance of {@link MobileEvent }
     * 
     */
    public MobileEvent createMobileEvent() {
        return new MobileEvent();
    }

    /**
     * Create an instance of {@link PurchaseItemsList }
     * 
     */
    public PurchaseItemsList createPurchaseItemsList() {
        return new PurchaseItemsList();
    }

    /**
     * Create an instance of {@link Actiity }
     * 
     */
    public Actiity createActiity() {
        return new Actiity();
    }

    /**
     * Create an instance of {@link EnterpriseEvent }
     * 
     */
    public EnterpriseEvent createEnterpriseEvent() {
        return new EnterpriseEvent();
    }

    /**
     * Create an instance of {@link Notification }
     * 
     */
    public Notification createNotification() {
        return new Notification();
    }

    /**
     * Create an instance of {@link OfferRequest }
     * 
     */
    public OfferRequest createOfferRequest() {
        return new OfferRequest();
    }

    /**
     * Create an instance of {@link OfferResponse }
     * 
     */
    public OfferResponse createOfferResponse() {
        return new OfferResponse();
    }

    /**
     * Create an instance of {@link ProcessList }
     * 
     */
    public ProcessList createProcessList() {
        return new ProcessList();
    }

    /**
     * Create an instance of {@link Process }
     * 
     */
    public Process createProcess() {
        return new Process();
    }

    /**
     * Create an instance of {@link AttributeList }
     * 
     */
    public AttributeList createAttributeList() {
        return new AttributeList();
    }

    /**
     * Create an instance of {@link ProcessAtribute }
     * 
     */
    public ProcessAtribute createProcessAtribute() {
        return new ProcessAtribute();
    }

    /**
     * Create an instance of {@link Jms }
     * 
     */
    public Jms createJms() {
        return new Jms();
    }

    /**
     * Create an instance of {@link PublicStream }
     * 
     */
    public PublicStream createPublicStream() {
        return new PublicStream();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link SiteStream }
     * 
     */
    public SiteStream createSiteStream() {
        return new SiteStream();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link UserStream }
     * 
     */
    public UserStream createUserStream() {
        return new UserStream();
    }

    /**
     * Create an instance of {@link DirectMessage }
     * 
     */
    public DirectMessage createDirectMessage() {
        return new DirectMessage();
    }

    /**
     * Create an instance of {@link GeoLocation }
     * 
     */
    public GeoLocation createGeoLocation() {
        return new GeoLocation();
    }

    /**
     * Create an instance of {@link GeolocationArray }
     * 
     */
    public GeolocationArray createGeolocationArray() {
        return new GeolocationArray();
    }

    /**
     * Create an instance of {@link HashTagEntities }
     * 
     */
    public HashTagEntities createHashTagEntities() {
        return new HashTagEntities();
    }

    /**
     * Create an instance of {@link MediaEntity }
     * 
     */
    public MediaEntity createMediaEntity() {
        return new MediaEntity();
    }

    /**
     * Create an instance of {@link Place }
     * 
     */
    public Place createPlace() {
        return new Place();
    }

    /**
     * Create an instance of {@link URLEntity }
     * 
     */
    public URLEntity createURLEntity() {
        return new URLEntity();
    }

    /**
     * Create an instance of {@link UserMentionedEntity }
     * 
     */
    public UserMentionedEntity createUserMentionedEntity() {
        return new UserMentionedEntity();
    }

    /**
     * Create an instance of {@link PaymentPrefference }
     * 
     */
    public PaymentPrefference createPaymentPrefference() {
        return new PaymentPrefference();
    }

    /**
     * Create an instance of {@link CustomerCBOList }
     * 
     */
    public CustomerCBOList createCustomerCBOList() {
        return new CustomerCBOList();
    }

    /**
     * Create an instance of {@link CustomerProfileCBO }
     * 
     */
    public CustomerProfileCBO createCustomerProfileCBO() {
        return new CustomerProfileCBO();
    }

    /**
     * Create an instance of {@link AddressList }
     * 
     */
    public AddressList createAddressList() {
        return new AddressList();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link PaymentPrefferenceList }
     * 
     */
    public PaymentPrefferenceList createPaymentPrefferenceList() {
        return new PaymentPrefferenceList();
    }

    /**
     * Create an instance of {@link LoyaltyProgram }
     * 
     */
    public LoyaltyProgram createLoyaltyProgram() {
        return new LoyaltyProgram();
    }

    /**
     * Create an instance of {@link LanguageSpokenList }
     * 
     */
    public LanguageSpokenList createLanguageSpokenList() {
        return new LanguageSpokenList();
    }

    /**
     * Create an instance of {@link PreferencesList }
     * 
     */
    public PreferencesList createPreferencesList() {
        return new PreferencesList();
    }

    /**
     * Create an instance of {@link SportsProfile }
     * 
     */
    public SportsProfile createSportsProfile() {
        return new SportsProfile();
    }

    /**
     * Create an instance of {@link FavouriteSportList }
     * 
     */
    public FavouriteSportList createFavouriteSportList() {
        return new FavouriteSportList();
    }

    /**
     * Create an instance of {@link Sport }
     * 
     */
    public Sport createSport() {
        return new Sport();
    }

    /**
     * Create an instance of {@link FavouritePlayerList }
     * 
     */
    public FavouritePlayerList createFavouritePlayerList() {
        return new FavouritePlayerList();
    }

    /**
     * Create an instance of {@link SportPlayer }
     * 
     */
    public SportPlayer createSportPlayer() {
        return new SportPlayer();
    }

    /**
     * Create an instance of {@link FavouriteTeamList }
     * 
     */
    public FavouriteTeamList createFavouriteTeamList() {
        return new FavouriteTeamList();
    }

    /**
     * Create an instance of {@link SportTeam }
     * 
     */
    public SportTeam createSportTeam() {
        return new SportTeam();
    }

    /**
     * Create an instance of {@link FoodProfile }
     * 
     */
    public FoodProfile createFoodProfile() {
        return new FoodProfile();
    }

    /**
     * Create an instance of {@link FavouriteFoodList }
     * 
     */
    public FavouriteFoodList createFavouriteFoodList() {
        return new FavouriteFoodList();
    }

    /**
     * Create an instance of {@link Food }
     * 
     */
    public Food createFood() {
        return new Food();
    }

    /**
     * Create an instance of {@link FavouriteRestaurantList }
     * 
     */
    public FavouriteRestaurantList createFavouriteRestaurantList() {
        return new FavouriteRestaurantList();
    }

    /**
     * Create an instance of {@link Restaurant }
     * 
     */
    public Restaurant createRestaurant() {
        return new Restaurant();
    }

    /**
     * Create an instance of {@link FavouriteChefList }
     * 
     */
    public FavouriteChefList createFavouriteChefList() {
        return new FavouriteChefList();
    }

    /**
     * Create an instance of {@link Chef }
     * 
     */
    public Chef createChef() {
        return new Chef();
    }

    /**
     * Create an instance of {@link DrinkProfile }
     * 
     */
    public DrinkProfile createDrinkProfile() {
        return new DrinkProfile();
    }

    /**
     * Create an instance of {@link FavouriteDrinkList }
     * 
     */
    public FavouriteDrinkList createFavouriteDrinkList() {
        return new FavouriteDrinkList();
    }

    /**
     * Create an instance of {@link Drink }
     * 
     */
    public Drink createDrink() {
        return new Drink();
    }

    /**
     * Create an instance of {@link FavouriteBarList }
     * 
     */
    public FavouriteBarList createFavouriteBarList() {
        return new FavouriteBarList();
    }

    /**
     * Create an instance of {@link Bar }
     * 
     */
    public Bar createBar() {
        return new Bar();
    }

    /**
     * Create an instance of {@link ServerDrinksList }
     * 
     */
    public ServerDrinksList createServerDrinksList() {
        return new ServerDrinksList();
    }

    /**
     * Create an instance of {@link MusicProfile }
     * 
     */
    public MusicProfile createMusicProfile() {
        return new MusicProfile();
    }

    /**
     * Create an instance of {@link FavouriteMusicTypeList }
     * 
     */
    public FavouriteMusicTypeList createFavouriteMusicTypeList() {
        return new FavouriteMusicTypeList();
    }

    /**
     * Create an instance of {@link FavouriteMusiciantList }
     * 
     */
    public FavouriteMusiciantList createFavouriteMusiciantList() {
        return new FavouriteMusiciantList();
    }

    /**
     * Create an instance of {@link Musician }
     * 
     */
    public Musician createMusician() {
        return new Musician();
    }

    /**
     * Create an instance of {@link FavouriteBandList }
     * 
     */
    public FavouriteBandList createFavouriteBandList() {
        return new FavouriteBandList();
    }

    /**
     * Create an instance of {@link Band }
     * 
     */
    public Band createBand() {
        return new Band();
    }

    /**
     * Create an instance of {@link ShoppingProfile }
     * 
     */
    public ShoppingProfile createShoppingProfile() {
        return new ShoppingProfile();
    }

    /**
     * Create an instance of {@link FavouriteMerchandiseList }
     * 
     */
    public FavouriteMerchandiseList createFavouriteMerchandiseList() {
        return new FavouriteMerchandiseList();
    }

    /**
     * Create an instance of {@link Merchandise }
     * 
     */
    public Merchandise createMerchandise() {
        return new Merchandise();
    }

    /**
     * Create an instance of {@link FavouriteStoreList }
     * 
     */
    public FavouriteStoreList createFavouriteStoreList() {
        return new FavouriteStoreList();
    }

    /**
     * Create an instance of {@link Store }
     * 
     */
    public Store createStore() {
        return new Store();
    }

    /**
     * Create an instance of {@link HealthProfile }
     * 
     */
    public HealthProfile createHealthProfile() {
        return new HealthProfile();
    }

    /**
     * Create an instance of {@link AllerygyList }
     * 
     */
    public AllerygyList createAllerygyList() {
        return new AllerygyList();
    }

    /**
     * Create an instance of {@link IllnessList }
     * 
     */
    public IllnessList createIllnessList() {
        return new IllnessList();
    }

    /**
     * Create an instance of {@link Illness }
     * 
     */
    public Illness createIllness() {
        return new Illness();
    }

    /**
     * Create an instance of {@link SocialMediaProfile }
     * 
     */
    public SocialMediaProfile createSocialMediaProfile() {
        return new SocialMediaProfile();
    }

    /**
     * Create an instance of {@link SocialMediaAppList }
     * 
     */
    public SocialMediaAppList createSocialMediaAppList() {
        return new SocialMediaAppList();
    }

    /**
     * Create an instance of {@link SocialMediaApp }
     * 
     */
    public SocialMediaApp createSocialMediaApp() {
        return new SocialMediaApp();
    }

    /**
     * Create an instance of {@link SocialMediaFriendList }
     * 
     */
    public SocialMediaFriendList createSocialMediaFriendList() {
        return new SocialMediaFriendList();
    }

    /**
     * Create an instance of {@link SocialMediaFriend }
     * 
     */
    public SocialMediaFriend createSocialMediaFriend() {
        return new SocialMediaFriend();
    }

    /**
     * Create an instance of {@link EntertainmentProfile }
     * 
     */
    public EntertainmentProfile createEntertainmentProfile() {
        return new EntertainmentProfile();
    }

    /**
     * Create an instance of {@link FavouriteCinemaList }
     * 
     */
    public FavouriteCinemaList createFavouriteCinemaList() {
        return new FavouriteCinemaList();
    }

    /**
     * Create an instance of {@link Cinema }
     * 
     */
    public Cinema createCinema() {
        return new Cinema();
    }

    /**
     * Create an instance of {@link CinemaBrand }
     * 
     */
    public CinemaBrand createCinemaBrand() {
        return new CinemaBrand();
    }

    /**
     * Create an instance of {@link FavouriteFilmList }
     * 
     */
    public FavouriteFilmList createFavouriteFilmList() {
        return new FavouriteFilmList();
    }

    /**
     * Create an instance of {@link Film }
     * 
     */
    public Film createFilm() {
        return new Film();
    }

    /**
     * Create an instance of {@link Music }
     * 
     */
    public Music createMusic() {
        return new Music();
    }

    /**
     * Create an instance of {@link Theater }
     * 
     */
    public Theater createTheater() {
        return new Theater();
    }

    /**
     * Create an instance of {@link GameFeed }
     * 
     */
    public GameFeed createGameFeed() {
        return new GameFeed();
    }

    /**
     * Create an instance of {@link Play }
     * 
     */
    public Play createPlay() {
        return new Play();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EventID")
    public JAXBElement<String> createEventID(String value) {
        return new JAXBElement<String>(_EventID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserID")
    public JAXBElement<String> createUserID(String value) {
        return new JAXBElement<String>(_UserID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ActivityType")
    public JAXBElement<String> createActivityType(String value) {
        return new JAXBElement<String>(_ActivityType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tstamp")
    public JAXBElement<String> createTstamp(String value) {
        return new JAXBElement<String>(_Tstamp_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BrowsedURL")
    public JAXBElement<String> createBrowsedURL(String value) {
        return new JAXBElement<String>(_BrowsedURL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BrowsedItemName")
    public JAXBElement<String> createBrowsedItemName(String value) {
        return new JAXBElement<String>(_BrowsedItemName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BrowsedItemCategory")
    public JAXBElement<String> createBrowsedItemCategory(String value) {
        return new JAXBElement<String>(_BrowsedItemCategory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BrowsedItemID")
    public JAXBElement<String> createBrowsedItemID(String value) {
        return new JAXBElement<String>(_BrowsedItemID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BrowsedItemBrand")
    public JAXBElement<String> createBrowsedItemBrand(String value) {
        return new JAXBElement<String>(_BrowsedItemBrand_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BrowsedItemPrice")
    public JAXBElement<Double> createBrowsedItemPrice(Double value) {
        return new JAXBElement<Double>(_BrowsedItemPrice_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BrowsedItemSize")
    public JAXBElement<String> createBrowsedItemSize(String value) {
        return new JAXBElement<String>(_BrowsedItemSize_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BrowsedItemGender")
    public JAXBElement<String> createBrowsedItemGender(String value) {
        return new JAXBElement<String>(_BrowsedItemGender_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PublishedContentCategory")
    public JAXBElement<String> createPublishedContentCategory(String value) {
        return new JAXBElement<String>(_PublishedContentCategory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PublishedContentTopic")
    public JAXBElement<String> createPublishedContentTopic(String value) {
        return new JAXBElement<String>(_PublishedContentTopic_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PublishedContentURL")
    public JAXBElement<String> createPublishedContentURL(String value) {
        return new JAXBElement<String>(_PublishedContentURL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PublishedContentID")
    public JAXBElement<String> createPublishedContentID(String value) {
        return new JAXBElement<String>(_PublishedContentID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PublishedContentData")
    public JAXBElement<String> createPublishedContentData(String value) {
        return new JAXBElement<String>(_PublishedContentData_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ExpiryDate")
    public JAXBElement<String> createExpiryDate(String value) {
        return new JAXBElement<String>(_ExpiryDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IntentName")
    public JAXBElement<String> createIntentName(String value) {
        return new JAXBElement<String>(_IntentName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IntentId")
    public JAXBElement<String> createIntentId(String value) {
        return new JAXBElement<String>(_IntentId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "eventId")
    public JAXBElement<String> createEventId(String value) {
        return new JAXBElement<String>(_EventId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userId_event")
    public JAXBElement<String> createUserIdEvent(String value) {
        return new JAXBElement<String>(_UserIdEvent_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "eventName")
    public JAXBElement<String> createEventName(String value) {
        return new JAXBElement<String>(_EventName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "eventType")
    public JAXBElement<String> createEventType(String value) {
        return new JAXBElement<String>(_EventType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "deviceId")
    public JAXBElement<String> createDeviceId(String value) {
        return new JAXBElement<String>(_DeviceId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "devicePhoneNumber")
    public JAXBElement<String> createDevicePhoneNumber(String value) {
        return new JAXBElement<String>(_DevicePhoneNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "geoLocationCoords")
    public JAXBElement<String> createGeoLocationCoords(String value) {
        return new JAXBElement<String>(_GeoLocationCoords_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "locationName")
    public JAXBElement<String> createLocationName(String value) {
        return new JAXBElement<String>(_LocationName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "seatNumber")
    public JAXBElement<String> createSeatNumber(String value) {
        return new JAXBElement<String>(_SeatNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "itemName")
    public JAXBElement<String> createItemName(String value) {
        return new JAXBElement<String>(_ItemName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "gameWin")
    public JAXBElement<Boolean> createGameWin(Boolean value) {
        return new JAXBElement<Boolean>(_GameWin_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "eventScorePlayer")
    public JAXBElement<String> createEventScorePlayer(String value) {
        return new JAXBElement<String>(_EventScorePlayer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "eventMessage")
    public JAXBElement<String> createEventMessage(String value) {
        return new JAXBElement<String>(_EventMessage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reqId_event")
    public JAXBElement<String> createReqIdEvent(String value) {
        return new JAXBElement<String>(_ReqIdEvent_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "applicationSrc")
    public JAXBElement<String> createApplicationSrc(String value) {
        return new JAXBElement<String>(_ApplicationSrc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mobile_activity")
    public JAXBElement<String> createMobileActivity(String value) {
        return new JAXBElement<String>(_MobileActivity_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "activity_object")
    public JAXBElement<String> createActivityObject(String value) {
        return new JAXBElement<String>(_ActivityObject_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "value")
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<String>(_Value_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "category")
    public JAXBElement<String> createCategory(String value) {
        return new JAXBElement<String>(_Category_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ent_event_id")
    public JAXBElement<String> createEntEventId(String value) {
        return new JAXBElement<String>(_EntEventId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ent_event_name")
    public JAXBElement<String> createEntEventName(String value) {
        return new JAXBElement<String>(_EntEventName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ent_event_type")
    public JAXBElement<String> createEntEventType(String value) {
        return new JAXBElement<String>(_EntEventType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ent_id")
    public JAXBElement<String> createEntId(String value) {
        return new JAXBElement<String>(_EntId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ent_app_source")
    public JAXBElement<String> createEntAppSource(String value) {
        return new JAXBElement<String>(_EntAppSource_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ent_user_id")
    public JAXBElement<String> createEntUserId(String value) {
        return new JAXBElement<String>(_EntUserId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ent_activity")
    public JAXBElement<String> createEntActivity(String value) {
        return new JAXBElement<String>(_EntActivity_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ent_activity_object")
    public JAXBElement<String> createEntActivityObject(String value) {
        return new JAXBElement<String>(_EntActivityObject_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ent_activity_object_uri")
    public JAXBElement<String> createEntActivityObjectUri(String value) {
        return new JAXBElement<String>(_EntActivityObjectUri_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ent_activity_category")
    public JAXBElement<String> createEntActivityCategory(String value) {
        return new JAXBElement<String>(_EntActivityCategory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ent_activity_context_category")
    public JAXBElement<String> createEntActivityContextCategory(String value) {
        return new JAXBElement<String>(_EntActivityContextCategory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ent_activity_context_content")
    public JAXBElement<String> createEntActivityContextContent(String value) {
        return new JAXBElement<String>(_EntActivityContextContent_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "id")
    public JAXBElement<String> createId(String value) {
        return new JAXBElement<String>(_Id_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userId_notification")
    public JAXBElement<String> createUserIdNotification(String value) {
        return new JAXBElement<String>(_UserIdNotification_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type")
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "notificationMessage")
    public JAXBElement<String> createNotificationMessage(String value) {
        return new JAXBElement<String>(_NotificationMessage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "source")
    public JAXBElement<String> createSource(String value) {
        return new JAXBElement<String>(_Source_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reqId_notification")
    public JAXBElement<String> createReqIdNotification(String value) {
        return new JAXBElement<String>(_ReqIdNotification_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "applicationSrc_notification")
    public JAXBElement<String> createApplicationSrcNotification(String value) {
        return new JAXBElement<String>(_ApplicationSrcNotification_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "payload")
    public JAXBElement<String> createPayload(String value) {
        return new JAXBElement<String>(_Payload_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userId_OfferReq")
    public JAXBElement<String> createUserIdOfferReq(String value) {
        return new JAXBElement<String>(_UserIdOfferReq_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reqId_offer")
    public JAXBElement<String> createReqIdOffer(String value) {
        return new JAXBElement<String>(_ReqIdOffer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userName")
    public JAXBElement<String> createUserName(String value) {
        return new JAXBElement<String>(_UserName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "offer")
    public JAXBElement<String> createOffer(String value) {
        return new JAXBElement<String>(_Offer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "offerType")
    public JAXBElement<String> createOfferType(String value) {
        return new JAXBElement<String>(_OfferType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "applicationSrc_offer")
    public JAXBElement<String> createApplicationSrcOffer(String value) {
        return new JAXBElement<String>(_ApplicationSrcOffer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "approve")
    public JAXBElement<Boolean> createApprove(Boolean value) {
        return new JAXBElement<Boolean>(_Approve_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "process_name")
    public JAXBElement<String> createProcessName(String value) {
        return new JAXBElement<String>(_ProcessName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "process_executable")
    public JAXBElement<String> createProcessExecutable(String value) {
        return new JAXBElement<String>(_ProcessExecutable_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pid")
    public JAXBElement<String> createPid(String value) {
        return new JAXBElement<String>(_Pid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "status")
    public JAXBElement<String> createStatus(String value) {
        return new JAXBElement<String>(_Status_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "start_phrase")
    public JAXBElement<String> createStartPhrase(String value) {
        return new JAXBElement<String>(_StartPhrase_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "end_phrase")
    public JAXBElement<String> createEndPhrase(String value) {
        return new JAXBElement<String>(_EndPhrase_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "attribute_name")
    public JAXBElement<String> createAttributeName(String value) {
        return new JAXBElement<String>(_AttributeName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "attribute_value")
    public JAXBElement<String> createAttributeValue(String value) {
        return new JAXBElement<String>(_AttributeValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "connect_url")
    public JAXBElement<String> createConnectUrl(String value) {
        return new JAXBElement<String>(_ConnectUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "jms_user")
    public JAXBElement<String> createJmsUser(String value) {
        return new JAXBElement<String>(_JmsUser_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "jms_pass")
    public JAXBElement<String> createJmsPass(String value) {
        return new JAXBElement<String>(_JmsPass_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_dest_name")
    public JAXBElement<String> createInDestName(String value) {
        return new JAXBElement<String>(_InDestName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_dest_type")
    public JAXBElement<String> createInDestType(String value) {
        return new JAXBElement<String>(_InDestType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "out_dest_name")
    public JAXBElement<String> createOutDestName(String value) {
        return new JAXBElement<String>(_OutDestName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "out_dest_type")
    public JAXBElement<String> createOutDestType(String value) {
        return new JAXBElement<String>(_OutDestType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "log_to_console")
    public JAXBElement<String> createLogToConsole(String value) {
        return new JAXBElement<String>(_LogToConsole_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "wait_for_process_end_milis")
    public JAXBElement<String> createWaitForProcessEndMilis(String value) {
        return new JAXBElement<String>(_WaitForProcessEndMilis_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", name = "userId")
    public JAXBElement<String> createUserId(String value) {
        return new JAXBElement<String>(_UserId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", name = "firstName")
    public JAXBElement<String> createFirstName(String value) {
        return new JAXBElement<String>(_FirstName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", name = "lastName")
    public JAXBElement<String> createLastName(String value) {
        return new JAXBElement<String>(_LastName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", name = "age")
    public JAXBElement<Integer> createAge(Integer value) {
        return new JAXBElement<Integer>(_Age_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", name = "cardNumber")
    public JAXBElement<String> createCardNumber(String value) {
        return new JAXBElement<String>(_CardNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", name = "cardType")
    public JAXBElement<String> createCardType(String value) {
        return new JAXBElement<String>(_CardType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", name = "issuingBank")
    public JAXBElement<String> createIssuingBank(String value) {
        return new JAXBElement<String>(_IssuingBank_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", name = "gender")
    public JAXBElement<String> createGender(String value) {
        return new JAXBElement<String>(_Gender_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", name = "middleName")
    public JAXBElement<String> createMiddleName(String value) {
        return new JAXBElement<String>(_MiddleName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", name = "dateOfBirth")
    public JAXBElement<String> createDateOfBirth(String value) {
        return new JAXBElement<String>(_DateOfBirth_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", name = "profession")
    public JAXBElement<String> createProfession(String value) {
        return new JAXBElement<String>(_Profession_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", name = "faceBookId")
    public JAXBElement<String> createFaceBookId(String value) {
        return new JAXBElement<String>(_FaceBookId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", name = "linkedInId")
    public JAXBElement<String> createLinkedInId(String value) {
        return new JAXBElement<String>(_LinkedInId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", name = "twitterId")
    public JAXBElement<String> createTwitterId(String value) {
        return new JAXBElement<String>(_TwitterId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", name = "streetNum")
    public JAXBElement<String> createStreetNum(String value) {
        return new JAXBElement<String>(_StreetNum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", name = "city")
    public JAXBElement<String> createCity(String value) {
        return new JAXBElement<String>(_City_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", name = "state")
    public JAXBElement<String> createState(String value) {
        return new JAXBElement<String>(_State_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", name = "country")
    public JAXBElement<String> createCountry(String value) {
        return new JAXBElement<String>(_Country_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", name = "loyaltyUserId")
    public JAXBElement<String> createLoyaltyUserId(String value) {
        return new JAXBElement<String>(_LoyaltyUserId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", name = "loyaltyProramName")
    public JAXBElement<String> createLoyaltyProramName(String value) {
        return new JAXBElement<String>(_LoyaltyProramName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", name = "loyaltyTier")
    public JAXBElement<String> createLoyaltyTier(String value) {
        return new JAXBElement<String>(_LoyaltyTier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", name = "totalAcumulatedPoints")
    public JAXBElement<Long> createTotalAcumulatedPoints(Long value) {
        return new JAXBElement<Long>(_TotalAcumulatedPoints_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd", name = "languageSpoken")
    public JAXBElement<String> createLanguageSpoken(String value) {
        return new JAXBElement<String>(_LanguageSpoken_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/SportsSchema.xsd", name = "sportType")
    public JAXBElement<String> createSportType(String value) {
        return new JAXBElement<String>(_SportType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/SportsSchema.xsd", name = "generalGameSentiment")
    public JAXBElement<String> createGeneralGameSentiment(String value) {
        return new JAXBElement<String>(_GeneralGameSentiment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/SportsSchema.xsd", name = "numGamesAttendedSeason")
    public JAXBElement<Long> createNumGamesAttendedSeason(Long value) {
        return new JAXBElement<Long>(_NumGamesAttendedSeason_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/SportsSchema.xsd", name = "numGamesAttendedTotal")
    public JAXBElement<Long> createNumGamesAttendedTotal(Long value) {
        return new JAXBElement<Long>(_NumGamesAttendedTotal_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/SportsSchema.xsd", name = "playerName")
    public JAXBElement<String> createPlayerName(String value) {
        return new JAXBElement<String>(_PlayerName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/SportsSchema.xsd", name = "teamName")
    public JAXBElement<String> createTeamName(String value) {
        return new JAXBElement<String>(_TeamName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/FoodSchema.xsd", name = "foodType")
    public JAXBElement<String> createFoodType(String value) {
        return new JAXBElement<String>(_FoodType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/FoodSchema.xsd", name = "dishName")
    public JAXBElement<String> createDishName(String value) {
        return new JAXBElement<String>(_DishName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/FoodSchema.xsd", name = "restaurantName")
    public JAXBElement<String> createRestaurantName(String value) {
        return new JAXBElement<String>(_RestaurantName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/FoodSchema.xsd", name = "restaurantType")
    public JAXBElement<String> createRestaurantType(String value) {
        return new JAXBElement<String>(_RestaurantType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/FoodSchema.xsd", name = "restaurantAddress")
    public JAXBElement<String> createRestaurantAddress(String value) {
        return new JAXBElement<String>(_RestaurantAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/FoodSchema.xsd", name = "chefName")
    public JAXBElement<String> createChefName(String value) {
        return new JAXBElement<String>(_ChefName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/FoodSchema.xsd", name = "chefCountryOfOrigin")
    public JAXBElement<String> createChefCountryOfOrigin(String value) {
        return new JAXBElement<String>(_ChefCountryOfOrigin_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/FoodSchema.xsd", name = "chefCookingStyle")
    public JAXBElement<String> createChefCookingStyle(String value) {
        return new JAXBElement<String>(_ChefCookingStyle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd", name = "drinkName")
    public JAXBElement<String> createDrinkName(String value) {
        return new JAXBElement<String>(_DrinkName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd", name = "drinkType")
    public JAXBElement<String> createDrinkType(String value) {
        return new JAXBElement<String>(_DrinkType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd", name = "drinkCategory")
    public JAXBElement<String> createDrinkCategory(String value) {
        return new JAXBElement<String>(_DrinkCategory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd", name = "drinkCountryofProvenance")
    public JAXBElement<String> createDrinkCountryofProvenance(String value) {
        return new JAXBElement<String>(_DrinkCountryofProvenance_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd", name = "barName")
    public JAXBElement<String> createBarName(String value) {
        return new JAXBElement<String>(_BarName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd", name = "barAddress")
    public JAXBElement<String> createBarAddress(String value) {
        return new JAXBElement<String>(_BarAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/MusicSchema.xsd", name = "musicType")
    public JAXBElement<String> createMusicType(String value) {
        return new JAXBElement<String>(_MusicType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/MusicSchema.xsd", name = "musicianName")
    public JAXBElement<String> createMusicianName(String value) {
        return new JAXBElement<String>(_MusicianName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/MusicSchema.xsd", name = "musicianCountryOfOrigin")
    public JAXBElement<String> createMusicianCountryOfOrigin(String value) {
        return new JAXBElement<String>(_MusicianCountryOfOrigin_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/MusicSchema.xsd", name = "musicianStyle")
    public JAXBElement<String> createMusicianStyle(String value) {
        return new JAXBElement<String>(_MusicianStyle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/MusicSchema.xsd", name = "bandName")
    public JAXBElement<String> createBandName(String value) {
        return new JAXBElement<String>(_BandName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/ShoppingSchema.xsd", name = "merchandiseName")
    public JAXBElement<String> createMerchandiseName(String value) {
        return new JAXBElement<String>(_MerchandiseName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/ShoppingSchema.xsd", name = "merchandiseType")
    public JAXBElement<String> createMerchandiseType(String value) {
        return new JAXBElement<String>(_MerchandiseType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/ShoppingSchema.xsd", name = "merchandiseMaxPrice")
    public JAXBElement<Double> createMerchandiseMaxPrice(Double value) {
        return new JAXBElement<Double>(_MerchandiseMaxPrice_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/ShoppingSchema.xsd", name = "merchandiseSize")
    public JAXBElement<String> createMerchandiseSize(String value) {
        return new JAXBElement<String>(_MerchandiseSize_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/ShoppingSchema.xsd", name = "merchandiseCategory")
    public JAXBElement<String> createMerchandiseCategory(String value) {
        return new JAXBElement<String>(_MerchandiseCategory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/ShoppingSchema.xsd", name = "storeName")
    public JAXBElement<String> createStoreName(String value) {
        return new JAXBElement<String>(_StoreName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/ShoppingSchema.xsd", name = "storeLocation")
    public JAXBElement<String> createStoreLocation(String value) {
        return new JAXBElement<String>(_StoreLocation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/HealthSchema.xsd", name = "allergy")
    public JAXBElement<String> createAllergy(String value) {
        return new JAXBElement<String>(_Allergy_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/HealthSchema.xsd", name = "illnessName")
    public JAXBElement<String> createIllnessName(String value) {
        return new JAXBElement<String>(_IllnessName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/SocialSchema.xsd", name = "userId_social")
    public JAXBElement<String> createUserIdSocial(String value) {
        return new JAXBElement<String>(_UserIdSocial_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/SocialSchema.xsd", name = "userPassword")
    public JAXBElement<String> createUserPassword(String value) {
        return new JAXBElement<String>(_UserPassword_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/SocialSchema.xsd", name = "userRole")
    public JAXBElement<String> createUserRole(String value) {
        return new JAXBElement<String>(_UserRole_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/SocialSchema.xsd", name = "socialAppName")
    public JAXBElement<String> createSocialAppName(String value) {
        return new JAXBElement<String>(_SocialAppName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/SocialSchema.xsd", name = "socialAppType")
    public JAXBElement<String> createSocialAppType(String value) {
        return new JAXBElement<String>(_SocialAppType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/SocialSchema.xsd", name = "friendName")
    public JAXBElement<String> createFriendName(String value) {
        return new JAXBElement<String>(_FriendName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/SocialSchema.xsd", name = "friendSocialGroup")
    public JAXBElement<String> createFriendSocialGroup(String value) {
        return new JAXBElement<String>(_FriendSocialGroup_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/EntSchema.xsd", name = "cinemaName")
    public JAXBElement<String> createCinemaName(String value) {
        return new JAXBElement<String>(_CinemaName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/EntSchema.xsd", name = "cinemaLocation")
    public JAXBElement<String> createCinemaLocation(String value) {
        return new JAXBElement<String>(_CinemaLocation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/EntSchema.xsd", name = "filmName")
    public JAXBElement<String> createFilmName(String value) {
        return new JAXBElement<String>(_FilmName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/EntSchema.xsd", name = "filmCategory")
    public JAXBElement<String> createFilmCategory(String value) {
        return new JAXBElement<String>(_FilmCategory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/EntSchema.xsd", name = "filmDate")
    public JAXBElement<String> createFilmDate(String value) {
        return new JAXBElement<String>(_FilmDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/MLSE_BW_Engage_Infrastructure/ShareResources/XSD/Schema.xsd", name = "game_name")
    public JAXBElement<String> createGameName(String value) {
        return new JAXBElement<String>(_GameName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/MLSE_BW_Engage_Infrastructure/ShareResources/XSD/Schema.xsd", name = "time")
    public JAXBElement<String> createTime(String value) {
        return new JAXBElement<String>(_Time_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/MLSE_BW_Engage_Infrastructure/ShareResources/XSD/Schema.xsd", name = "period")
    public JAXBElement<String> createPeriod(String value) {
        return new JAXBElement<String>(_Period_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/MLSE_BW_Engage_Infrastructure/ShareResources/XSD/Schema.xsd", name = "team")
    public JAXBElement<String> createTeam(String value) {
        return new JAXBElement<String>(_Team_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/schemas/MLSE_BW_Engage_Infrastructure/ShareResources/XSD/Schema.xsd", name = "detail")
    public JAXBElement<String> createDetail(String value) {
        return new JAXBElement<String>(_Detail_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type", scope = MediaEntity.class)
    public JAXBElement<String> createMediaEntityType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, MediaEntity.class, value);
    }

}
