//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 05:58:39 PM EST 
//


package com.extemp.cem.profiles;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/SportsSchema.xsd}SportsProfile" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/FoodSchema.xsd}FoodProfile" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd}DrinkProfile" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/MusicSchema.xsd}MusicProfile" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/ShoppingSchema.xsd}ShoppingProfile" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/HealthSchema.xsd}HealthProfile" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/SocialSchema.xsd}SocialMediaProfile" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/EntSchema.xsd}EntertainmentProfile" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sportsProfile",
    "foodProfile",
    "drinkProfile",
    "musicProfile",
    "shoppingProfile",
    "healthProfile",
    "socialMediaProfile",
    "entertainmentProfile"
})
@XmlRootElement(name = "preferencesList", namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/CustProfileSchema.xsd")
public class PreferencesList {

    @XmlElement(name = "SportsProfile", namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/SportsSchema.xsd")
    protected SportsProfile sportsProfile;
    @XmlElement(name = "FoodProfile", namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/FoodSchema.xsd")
    protected FoodProfile foodProfile;
    @XmlElement(name = "DrinkProfile", namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/DrinkSchema.xsd")
    protected DrinkProfile drinkProfile;
    @XmlElement(name = "MusicProfile", namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/MusicSchema.xsd")
    protected MusicProfile musicProfile;
    @XmlElement(name = "ShoppingProfile", namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/ShoppingSchema.xsd")
    protected ShoppingProfile shoppingProfile;
    @XmlElement(name = "HealthProfile", namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/HealthSchema.xsd")
    protected HealthProfile healthProfile;
    @XmlElement(name = "SocialMediaProfile", namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/SocialSchema.xsd")
    protected SocialMediaProfile socialMediaProfile;
    @XmlElement(name = "EntertainmentProfile", namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/EntSchema.xsd")
    protected EntertainmentProfile entertainmentProfile;

    /**
     * Gets the value of the sportsProfile property.
     * 
     * @return
     *     possible object is
     *     {@link SportsProfile }
     *     
     */
    public SportsProfile getSportsProfile() {
        return sportsProfile;
    }

    /**
     * Sets the value of the sportsProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link SportsProfile }
     *     
     */
    public void setSportsProfile(SportsProfile value) {
        this.sportsProfile = value;
    }

    /**
     * Gets the value of the foodProfile property.
     * 
     * @return
     *     possible object is
     *     {@link FoodProfile }
     *     
     */
    public FoodProfile getFoodProfile() {
        return foodProfile;
    }

    /**
     * Sets the value of the foodProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link FoodProfile }
     *     
     */
    public void setFoodProfile(FoodProfile value) {
        this.foodProfile = value;
    }

    /**
     * Gets the value of the drinkProfile property.
     * 
     * @return
     *     possible object is
     *     {@link DrinkProfile }
     *     
     */
    public DrinkProfile getDrinkProfile() {
        return drinkProfile;
    }

    /**
     * Sets the value of the drinkProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link DrinkProfile }
     *     
     */
    public void setDrinkProfile(DrinkProfile value) {
        this.drinkProfile = value;
    }

    /**
     * Gets the value of the musicProfile property.
     * 
     * @return
     *     possible object is
     *     {@link MusicProfile }
     *     
     */
    public MusicProfile getMusicProfile() {
        return musicProfile;
    }

    /**
     * Sets the value of the musicProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link MusicProfile }
     *     
     */
    public void setMusicProfile(MusicProfile value) {
        this.musicProfile = value;
    }

    /**
     * Gets the value of the shoppingProfile property.
     * 
     * @return
     *     possible object is
     *     {@link ShoppingProfile }
     *     
     */
    public ShoppingProfile getShoppingProfile() {
        return shoppingProfile;
    }

    /**
     * Sets the value of the shoppingProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShoppingProfile }
     *     
     */
    public void setShoppingProfile(ShoppingProfile value) {
        this.shoppingProfile = value;
    }

    /**
     * Gets the value of the healthProfile property.
     * 
     * @return
     *     possible object is
     *     {@link HealthProfile }
     *     
     */
    public HealthProfile getHealthProfile() {
        return healthProfile;
    }

    /**
     * Sets the value of the healthProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link HealthProfile }
     *     
     */
    public void setHealthProfile(HealthProfile value) {
        this.healthProfile = value;
    }

    /**
     * Gets the value of the socialMediaProfile property.
     * 
     * @return
     *     possible object is
     *     {@link SocialMediaProfile }
     *     
     */
    public SocialMediaProfile getSocialMediaProfile() {
        return socialMediaProfile;
    }

    /**
     * Sets the value of the socialMediaProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link SocialMediaProfile }
     *     
     */
    public void setSocialMediaProfile(SocialMediaProfile value) {
        this.socialMediaProfile = value;
    }

    /**
     * Gets the value of the entertainmentProfile property.
     * 
     * @return
     *     possible object is
     *     {@link EntertainmentProfile }
     *     
     */
    public EntertainmentProfile getEntertainmentProfile() {
        return entertainmentProfile;
    }

    /**
     * Sets the value of the entertainmentProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntertainmentProfile }
     *     
     */
    public void setEntertainmentProfile(EntertainmentProfile value) {
        this.entertainmentProfile = value;
    }

}
