//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 05:58:39 PM EST 
//


package com.extemp.cem.profiles;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}process_name" minOccurs="0"/&gt;
 *         &lt;element ref="{}process_executable" minOccurs="0"/&gt;
 *         &lt;element ref="{}pid" minOccurs="0"/&gt;
 *         &lt;element ref="{}status" minOccurs="0"/&gt;
 *         &lt;element ref="{}start_phrase" minOccurs="0"/&gt;
 *         &lt;element ref="{}end_phrase" minOccurs="0"/&gt;
 *         &lt;element ref="{}attribute_list" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "processName",
    "processExecutable",
    "pid",
    "status",
    "startPhrase",
    "endPhrase",
    "attributeList"
})
@XmlRootElement(name = "Process")
public class Process {

    @XmlElement(name = "process_name")
    protected String processName;
    @XmlElement(name = "process_executable")
    protected String processExecutable;
    protected String pid;
    protected String status;
    @XmlElement(name = "start_phrase")
    protected String startPhrase;
    @XmlElement(name = "end_phrase")
    protected String endPhrase;
    @XmlElement(name = "attribute_list")
    protected AttributeList attributeList;

    /**
     * Gets the value of the processName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessName() {
        return processName;
    }

    /**
     * Sets the value of the processName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessName(String value) {
        this.processName = value;
    }

    /**
     * Gets the value of the processExecutable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessExecutable() {
        return processExecutable;
    }

    /**
     * Sets the value of the processExecutable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessExecutable(String value) {
        this.processExecutable = value;
    }

    /**
     * Gets the value of the pid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPid() {
        return pid;
    }

    /**
     * Sets the value of the pid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPid(String value) {
        this.pid = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the startPhrase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartPhrase() {
        return startPhrase;
    }

    /**
     * Sets the value of the startPhrase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartPhrase(String value) {
        this.startPhrase = value;
    }

    /**
     * Gets the value of the endPhrase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndPhrase() {
        return endPhrase;
    }

    /**
     * Sets the value of the endPhrase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndPhrase(String value) {
        this.endPhrase = value;
    }

    /**
     * Gets the value of the attributeList property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeList }
     *     
     */
    public AttributeList getAttributeList() {
        return attributeList;
    }

    /**
     * Sets the value of the attributeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeList }
     *     
     */
    public void setAttributeList(AttributeList value) {
        this.attributeList = value;
    }

}
