//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 05:58:39 PM EST 
//


package com.extemp.cem.profiles;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/ShoppingSchema.xsd}favouriteMerchandiseList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/ShoppingSchema.xsd}favouriteStoreList" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "favouriteMerchandiseList",
    "favouriteStoreList"
})
@XmlRootElement(name = "ShoppingProfile", namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/ShoppingSchema.xsd")
public class ShoppingProfile {

    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/ShoppingSchema.xsd")
    protected FavouriteMerchandiseList favouriteMerchandiseList;
    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/ShoppingSchema.xsd")
    protected FavouriteStoreList favouriteStoreList;

    /**
     * Gets the value of the favouriteMerchandiseList property.
     * 
     * @return
     *     possible object is
     *     {@link FavouriteMerchandiseList }
     *     
     */
    public FavouriteMerchandiseList getFavouriteMerchandiseList() {
        return favouriteMerchandiseList;
    }

    /**
     * Sets the value of the favouriteMerchandiseList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FavouriteMerchandiseList }
     *     
     */
    public void setFavouriteMerchandiseList(FavouriteMerchandiseList value) {
        this.favouriteMerchandiseList = value;
    }

    /**
     * Gets the value of the favouriteStoreList property.
     * 
     * @return
     *     possible object is
     *     {@link FavouriteStoreList }
     *     
     */
    public FavouriteStoreList getFavouriteStoreList() {
        return favouriteStoreList;
    }

    /**
     * Sets the value of the favouriteStoreList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FavouriteStoreList }
     *     
     */
    public void setFavouriteStoreList(FavouriteStoreList value) {
        this.favouriteStoreList = value;
    }

}
