//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 05:58:39 PM EST 
//


package com.extemp.cem.profiles;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/SportsSchema.xsd}favouriteSportList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/SportsSchema.xsd}favouritePlayerList" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/CEM/SharedResources/XSD/SportsSchema.xsd}favouriteTeamList" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "favouriteSportList",
    "favouritePlayerList",
    "favouriteTeamList"
})
@XmlRootElement(name = "SportsProfile", namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/SportsSchema.xsd")
public class SportsProfile {

    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/SportsSchema.xsd")
    protected FavouriteSportList favouriteSportList;
    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/SportsSchema.xsd")
    protected FavouritePlayerList favouritePlayerList;
    @XmlElement(namespace = "http://www.tibco.com/schemas/CEM/SharedResources/XSD/SportsSchema.xsd")
    protected FavouriteTeamList favouriteTeamList;

    /**
     * Gets the value of the favouriteSportList property.
     * 
     * @return
     *     possible object is
     *     {@link FavouriteSportList }
     *     
     */
    public FavouriteSportList getFavouriteSportList() {
        return favouriteSportList;
    }

    /**
     * Sets the value of the favouriteSportList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FavouriteSportList }
     *     
     */
    public void setFavouriteSportList(FavouriteSportList value) {
        this.favouriteSportList = value;
    }

    /**
     * Gets the value of the favouritePlayerList property.
     * 
     * @return
     *     possible object is
     *     {@link FavouritePlayerList }
     *     
     */
    public FavouritePlayerList getFavouritePlayerList() {
        return favouritePlayerList;
    }

    /**
     * Sets the value of the favouritePlayerList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FavouritePlayerList }
     *     
     */
    public void setFavouritePlayerList(FavouritePlayerList value) {
        this.favouritePlayerList = value;
    }

    /**
     * Gets the value of the favouriteTeamList property.
     * 
     * @return
     *     possible object is
     *     {@link FavouriteTeamList }
     *     
     */
    public FavouriteTeamList getFavouriteTeamList() {
        return favouriteTeamList;
    }

    /**
     * Sets the value of the favouriteTeamList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FavouriteTeamList }
     *     
     */
    public void setFavouriteTeamList(FavouriteTeamList value) {
        this.favouriteTeamList = value;
    }

}
