//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.1-05/30/2003 05:06 AM(java_re)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2003.07.30 at 06:15:01 EDT 
//


package com.perpetual.rp.util.jaxb;

public interface CollectionCriteria {


    /**
     * 
     * @return possible object is
     * {@link com.perpetual.rp.util.jaxb.SeverityList}
     */
    com.perpetual.rp.util.jaxb.SeverityList getSeverityList();

    /**
     * 
     * @param value allowed object is
     * {@link com.perpetual.rp.util.jaxb.SeverityList}
     */
    void setSeverityList(com.perpetual.rp.util.jaxb.SeverityList value);

    /**
     * 
     * @return possible object is
     * {@link com.perpetual.rp.util.jaxb.FacilityList}
     */
    com.perpetual.rp.util.jaxb.FacilityList getFacilityList();

    /**
     * 
     * @param value allowed object is
     * {@link com.perpetual.rp.util.jaxb.FacilityList}
     */
    void setFacilityList(com.perpetual.rp.util.jaxb.FacilityList value);

    /**
     * 
     * @return possible object is
     * {@link com.perpetual.rp.util.jaxb.HostList}
     */
    com.perpetual.rp.util.jaxb.HostList getHostList();

    /**
     * 
     * @param value allowed object is
     * {@link com.perpetual.rp.util.jaxb.HostList}
     */
    void setHostList(com.perpetual.rp.util.jaxb.HostList value);

}
