//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.1-05/30/2003 05:06 AM(java_re)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2003.07.30 at 06:15:01 EDT 
//


package com.perpetual.rp.util.jaxb;

public interface RecordProcessorConfig {


    /**
     * 
     * @return possible object is
     * {@link com.perpetual.rp.util.jaxb.SummaryCollection}
     */
    com.perpetual.rp.util.jaxb.SummaryCollection getSummaryCollection();

    /**
     * 
     * @param value allowed object is
     * {@link com.perpetual.rp.util.jaxb.SummaryCollection}
     */
    void setSummaryCollection(com.perpetual.rp.util.jaxb.SummaryCollection value);

}
