//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.1-05/30/2003 05:06 AM(java_re)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2003.07.30 at 06:15:01 EDT 
//


package com.perpetual.rp.util.jaxb;

public interface VendorCriteria {


    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getType();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setType(java.lang.String value);

    /**
     * Gets the value of the VendorCriterion property.
     * 
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there's any setter method for the VendorCriterion property.
     * 
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVendorCriterion().add(newItem);
     * </pre>
     * 
     * 
     * Objects of the following type(s) are allowed in the list
     * {@link com.perpetual.rp.util.jaxb.VendorCriterion}
     * 
     */
    java.util.List getVendorCriterion();

    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getName();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setName(java.lang.String value);

}
