//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 05:58:41 PM EST 
//


package com.extemp.cem.events.payloads;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}userId_profile" minOccurs="0"/&gt;
 *         &lt;element ref="{}location" minOccurs="0"/&gt;
 *         &lt;element ref="{}twitter_id" minOccurs="0"/&gt;
 *         &lt;element ref="{}fb_id" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userIdProfile",
    "location",
    "twitterId",
    "fbId"
})
@XmlRootElement(name = "FanProfileRequest")
public class FanProfileRequest {

    @XmlElement(name = "userId_profile")
    protected String userIdProfile;
    protected String location;
    @XmlElement(name = "twitter_id")
    protected String twitterId;
    @XmlElement(name = "fb_id")
    protected String fbId;

    /**
     * Gets the value of the userIdProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserIdProfile() {
        return userIdProfile;
    }

    /**
     * Sets the value of the userIdProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserIdProfile(String value) {
        this.userIdProfile = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the twitterId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTwitterId() {
        return twitterId;
    }

    /**
     * Sets the value of the twitterId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTwitterId(String value) {
        this.twitterId = value;
    }

    /**
     * Gets the value of the fbId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFbId() {
        return fbId;
    }

    /**
     * Sets the value of the fbId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFbId(String value) {
        this.fbId = value;
    }

}
