//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 05:58:41 PM EST 
//


package com.extemp.cem.events.payloads;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.extemp.cem.events.payloads package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UserIdAuction_QNAME = new QName("", "userId_auction");
    private final static QName _CurrentBid_QNAME = new QName("", "current_bid");
    private final static QName _Winner_QNAME = new QName("", "winner");
    private final static QName _ApplicationSrcAuction_QNAME = new QName("", "applicationSrc_auction");
    private final static QName _AuctionObjectId_QNAME = new QName("", "auctionObjectId");
    private final static QName _RunningTotal_QNAME = new QName("", "running_total");
    private final static QName _Status_QNAME = new QName("", "status");
    private final static QName _UserIdProfile_QNAME = new QName("", "userId_profile");
    private final static QName _Location_QNAME = new QName("", "location");
    private final static QName _TwitterId_QNAME = new QName("", "twitter_id");
    private final static QName _FbId_QNAME = new QName("", "fb_id");
    private final static QName _ReplyStr_QNAME = new QName("", "reply_str");
    private final static QName _ItemId_QNAME = new QName("", "item_id");
    private final static QName _ItemName_QNAME = new QName("", "item_name");
    private final static QName _Price_QNAME = new QName("", "price");
    private final static QName _Quantity_QNAME = new QName("", "quantity");
    private final static QName _OrderId_QNAME = new QName("", "order_id");
    private final static QName _UserIdOrder_QNAME = new QName("", "userId_order");
    private final static QName _Tstamp_QNAME = new QName("", "tstamp");
    private final static QName _EmployeeId_QNAME = new QName("", "employee_id");
    private final static QName _Kiosk_QNAME = new QName("", "kiosk");
    private final static QName _SeatNumber_QNAME = new QName("", "seat_number");
    private final static QName _TotalOrderValue_QNAME = new QName("", "total_order_value");
    private final static QName _Tip_QNAME = new QName("", "tip");
    private final static QName _Tax_QNAME = new QName("", "tax");
    private final static QName _PaymentMethod_QNAME = new QName("", "payment_method");
    private final static QName _PaymentNumber_QNAME = new QName("", "payment_number");
    private final static QName _LoyaltyPointsValue_QNAME = new QName("", "loyalty_points_value");
    private final static QName _PurchaseType_QNAME = new QName("", "purchase_type");
    private final static QName _ApplicationSrcOrder_QNAME = new QName("", "applicationSrc_order");
    private final static QName _StatusStr_QNAME = new QName("", "status_str");
    private final static QName _SocialId_QNAME = new QName("", "social_id");
    private final static QName _GameIdSocial_QNAME = new QName("", "game_id_social");
    private final static QName _Date_QNAME = new QName("", "date");
    private final static QName _Message_QNAME = new QName("", "message");
    private final static QName _Category_QNAME = new QName("", "category");
    private final static QName _SentimentScore_QNAME = new QName("", "sentiment_score");
    private final static QName _NumRetweets_QNAME = new QName("", "num_retweets");
    private final static QName _NumFollowers_QNAME = new QName("", "num_followers");
    private final static QName _NumFriends_QNAME = new QName("", "num_friends");
    private final static QName _ReqIdSocial_QNAME = new QName("", "req_id_social");
    private final static QName _UserIdTicket_QNAME = new QName("", "userId_ticket");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _SeatNum_QNAME = new QName("", "seat_num");
    private final static QName _ReqIdTicket_QNAME = new QName("", "req_id_ticket");
    private final static QName _ApplicationSrcTicket_QNAME = new QName("", "applicationSrc_ticket");
    private final static QName _ReplyStatus_QNAME = new QName("", "reply_status");
    private final static QName _UserIdVote_QNAME = new QName("", "userId_vote");
    private final static QName _GameIdVote_QNAME = new QName("", "game_id_vote");
    private final static QName _Vote_QNAME = new QName("", "vote");
    private final static QName _ApplicationSrcVote_QNAME = new QName("", "applicationSrc_vote");
    private final static QName _VoteResponseStr_QNAME = new QName("", "vote_response_str");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.extemp.cem.events.payloads
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AuctionBidSubmit }
     * 
     */
    public AuctionBidSubmit createAuctionBidSubmit() {
        return new AuctionBidSubmit();
    }

    /**
     * Create an instance of {@link AuctionBidReply }
     * 
     */
    public AuctionBidReply createAuctionBidReply() {
        return new AuctionBidReply();
    }

    /**
     * Create an instance of {@link FanProfileRequest }
     * 
     */
    public FanProfileRequest createFanProfileRequest() {
        return new FanProfileRequest();
    }

    /**
     * Create an instance of {@link FanProfileReply }
     * 
     */
    public FanProfileReply createFanProfileReply() {
        return new FanProfileReply();
    }

    /**
     * Create an instance of {@link PurchaseItem }
     * 
     */
    public PurchaseItem createPurchaseItem() {
        return new PurchaseItem();
    }

    /**
     * Create an instance of {@link PurchaseItemList }
     * 
     */
    public PurchaseItemList createPurchaseItemList() {
        return new PurchaseItemList();
    }

    /**
     * Create an instance of {@link PurchaseRequest }
     * 
     */
    public PurchaseRequest createPurchaseRequest() {
        return new PurchaseRequest();
    }

    /**
     * Create an instance of {@link PurchaseReply }
     * 
     */
    public PurchaseReply createPurchaseReply() {
        return new PurchaseReply();
    }

    /**
     * Create an instance of {@link SocialFeedEvent }
     * 
     */
    public SocialFeedEvent createSocialFeedEvent() {
        return new SocialFeedEvent();
    }

    /**
     * Create an instance of {@link TicketRequest }
     * 
     */
    public TicketRequest createTicketRequest() {
        return new TicketRequest();
    }

    /**
     * Create an instance of {@link TicketReply }
     * 
     */
    public TicketReply createTicketReply() {
        return new TicketReply();
    }

    /**
     * Create an instance of {@link VoteRequest }
     * 
     */
    public VoteRequest createVoteRequest() {
        return new VoteRequest();
    }

    /**
     * Create an instance of {@link VoteReply }
     * 
     */
    public VoteReply createVoteReply() {
        return new VoteReply();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userId_auction")
    public JAXBElement<String> createUserIdAuction(String value) {
        return new JAXBElement<String>(_UserIdAuction_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "current_bid")
    public JAXBElement<Double> createCurrentBid(Double value) {
        return new JAXBElement<Double>(_CurrentBid_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "winner")
    public JAXBElement<String> createWinner(String value) {
        return new JAXBElement<String>(_Winner_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "applicationSrc_auction")
    public JAXBElement<String> createApplicationSrcAuction(String value) {
        return new JAXBElement<String>(_ApplicationSrcAuction_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "auctionObjectId")
    public JAXBElement<String> createAuctionObjectId(String value) {
        return new JAXBElement<String>(_AuctionObjectId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "running_total")
    public JAXBElement<Double> createRunningTotal(Double value) {
        return new JAXBElement<Double>(_RunningTotal_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "status")
    public JAXBElement<String> createStatus(String value) {
        return new JAXBElement<String>(_Status_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userId_profile")
    public JAXBElement<String> createUserIdProfile(String value) {
        return new JAXBElement<String>(_UserIdProfile_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "location")
    public JAXBElement<String> createLocation(String value) {
        return new JAXBElement<String>(_Location_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "twitter_id")
    public JAXBElement<String> createTwitterId(String value) {
        return new JAXBElement<String>(_TwitterId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fb_id")
    public JAXBElement<String> createFbId(String value) {
        return new JAXBElement<String>(_FbId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reply_str")
    public JAXBElement<String> createReplyStr(String value) {
        return new JAXBElement<String>(_ReplyStr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "item_id")
    public JAXBElement<String> createItemId(String value) {
        return new JAXBElement<String>(_ItemId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "item_name")
    public JAXBElement<String> createItemName(String value) {
        return new JAXBElement<String>(_ItemName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "price")
    public JAXBElement<Double> createPrice(Double value) {
        return new JAXBElement<Double>(_Price_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "quantity")
    public JAXBElement<Integer> createQuantity(Integer value) {
        return new JAXBElement<Integer>(_Quantity_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "order_id")
    public JAXBElement<String> createOrderId(String value) {
        return new JAXBElement<String>(_OrderId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userId_order")
    public JAXBElement<String> createUserIdOrder(String value) {
        return new JAXBElement<String>(_UserIdOrder_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tstamp")
    public JAXBElement<String> createTstamp(String value) {
        return new JAXBElement<String>(_Tstamp_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "employee_id")
    public JAXBElement<String> createEmployeeId(String value) {
        return new JAXBElement<String>(_EmployeeId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kiosk")
    public JAXBElement<String> createKiosk(String value) {
        return new JAXBElement<String>(_Kiosk_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "seat_number")
    public JAXBElement<String> createSeatNumber(String value) {
        return new JAXBElement<String>(_SeatNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "total_order_value")
    public JAXBElement<Double> createTotalOrderValue(Double value) {
        return new JAXBElement<Double>(_TotalOrderValue_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tip")
    public JAXBElement<Double> createTip(Double value) {
        return new JAXBElement<Double>(_Tip_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tax")
    public JAXBElement<Double> createTax(Double value) {
        return new JAXBElement<Double>(_Tax_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "payment_method")
    public JAXBElement<String> createPaymentMethod(String value) {
        return new JAXBElement<String>(_PaymentMethod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "payment_number")
    public JAXBElement<String> createPaymentNumber(String value) {
        return new JAXBElement<String>(_PaymentNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "loyalty_points_value")
    public JAXBElement<Long> createLoyaltyPointsValue(Long value) {
        return new JAXBElement<Long>(_LoyaltyPointsValue_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "purchase_type")
    public JAXBElement<String> createPurchaseType(String value) {
        return new JAXBElement<String>(_PurchaseType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "applicationSrc_order")
    public JAXBElement<String> createApplicationSrcOrder(String value) {
        return new JAXBElement<String>(_ApplicationSrcOrder_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "status_str")
    public JAXBElement<String> createStatusStr(String value) {
        return new JAXBElement<String>(_StatusStr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "social_id")
    public JAXBElement<String> createSocialId(String value) {
        return new JAXBElement<String>(_SocialId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "game_id_social")
    public JAXBElement<String> createGameIdSocial(String value) {
        return new JAXBElement<String>(_GameIdSocial_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "date")
    public JAXBElement<String> createDate(String value) {
        return new JAXBElement<String>(_Date_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "message")
    public JAXBElement<String> createMessage(String value) {
        return new JAXBElement<String>(_Message_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "category")
    public JAXBElement<String> createCategory(String value) {
        return new JAXBElement<String>(_Category_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sentiment_score")
    public JAXBElement<String> createSentimentScore(String value) {
        return new JAXBElement<String>(_SentimentScore_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "num_retweets")
    public JAXBElement<Integer> createNumRetweets(Integer value) {
        return new JAXBElement<Integer>(_NumRetweets_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "num_followers")
    public JAXBElement<Integer> createNumFollowers(Integer value) {
        return new JAXBElement<Integer>(_NumFollowers_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "num_friends")
    public JAXBElement<Integer> createNumFriends(Integer value) {
        return new JAXBElement<Integer>(_NumFriends_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "req_id_social")
    public JAXBElement<String> createReqIdSocial(String value) {
        return new JAXBElement<String>(_ReqIdSocial_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userId_ticket")
    public JAXBElement<String> createUserIdTicket(String value) {
        return new JAXBElement<String>(_UserIdTicket_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "seat_num")
    public JAXBElement<String> createSeatNum(String value) {
        return new JAXBElement<String>(_SeatNum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "req_id_ticket")
    public JAXBElement<String> createReqIdTicket(String value) {
        return new JAXBElement<String>(_ReqIdTicket_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "applicationSrc_ticket")
    public JAXBElement<String> createApplicationSrcTicket(String value) {
        return new JAXBElement<String>(_ApplicationSrcTicket_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reply_status")
    public JAXBElement<String> createReplyStatus(String value) {
        return new JAXBElement<String>(_ReplyStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userId_vote")
    public JAXBElement<String> createUserIdVote(String value) {
        return new JAXBElement<String>(_UserIdVote_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "game_id_vote")
    public JAXBElement<String> createGameIdVote(String value) {
        return new JAXBElement<String>(_GameIdVote_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "vote")
    public JAXBElement<String> createVote(String value) {
        return new JAXBElement<String>(_Vote_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "applicationSrc_vote")
    public JAXBElement<String> createApplicationSrcVote(String value) {
        return new JAXBElement<String>(_ApplicationSrcVote_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "vote_response_str")
    public JAXBElement<String> createVoteResponseStr(String value) {
        return new JAXBElement<String>(_VoteResponseStr_QNAME, String.class, null, value);
    }

}
