//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 05:58:41 PM EST 
//


package com.extemp.cem.events.payloads;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}userId_ticket" minOccurs="0"/&gt;
 *         &lt;element ref="{}name" minOccurs="0"/&gt;
 *         &lt;element ref="{}seat_num" minOccurs="0"/&gt;
 *         &lt;element ref="{}req_id_ticket" minOccurs="0"/&gt;
 *         &lt;element ref="{}applicationSrc_ticket" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userIdTicket",
    "name",
    "seatNum",
    "reqIdTicket",
    "applicationSrcTicket"
})
@XmlRootElement(name = "TicketRequest")
public class TicketRequest {

    @XmlElement(name = "userId_ticket")
    protected String userIdTicket;
    protected String name;
    @XmlElement(name = "seat_num")
    protected String seatNum;
    @XmlElement(name = "req_id_ticket")
    protected String reqIdTicket;
    @XmlElement(name = "applicationSrc_ticket")
    protected String applicationSrcTicket;

    /**
     * Gets the value of the userIdTicket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserIdTicket() {
        return userIdTicket;
    }

    /**
     * Sets the value of the userIdTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserIdTicket(String value) {
        this.userIdTicket = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the seatNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeatNum() {
        return seatNum;
    }

    /**
     * Sets the value of the seatNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeatNum(String value) {
        this.seatNum = value;
    }

    /**
     * Gets the value of the reqIdTicket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqIdTicket() {
        return reqIdTicket;
    }

    /**
     * Sets the value of the reqIdTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqIdTicket(String value) {
        this.reqIdTicket = value;
    }

    /**
     * Gets the value of the applicationSrcTicket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationSrcTicket() {
        return applicationSrcTicket;
    }

    /**
     * Sets the value of the applicationSrcTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationSrcTicket(String value) {
        this.applicationSrcTicket = value;
    }

}
